### ISSUE TITLE
Funder cannot be different from rightsholder in organisation.yml

### ISSUE THREAD

**Issue by wlangera** [inbo/checklist#128]
Hi

At this point the funder and rightsholder cannot be different.
Yet this can be the case in some instances.

**organisation.yml**

```
community: b3
email: NA_character_
github: b-cubed-eu
funder: European Union ...
rightsholder: Research Institute for Nature and Forest (INBO)
organisation:
  inbo.be:
    affiliation:
    - Research Institute for Nature and Forest (INBO)
    - Instituut voor Natuur- en Bosonderzoek (INBO)
    - Institut de Recherche sur la Nature et les Forêts (INBO)
    - Institut für Natur- und Waldforschung (INBO)
    orcid: yes
```

Will throw this error:

```
Error in check_authors(read_organisation(x$get_path), this_desc = this_desc) : 
  TO DO: handle funder not equal to rightsholder
```
