### ISSUE TITLE
Recommend use of ROR for INBO copyright holder in DESCRIPTION

### ISSUE THREAD

**Issue by peterdesmet** [inbo/checklist#153]
ROR identifiers are the recommended identifiers for organizations, cf. ORCID for people. Just like ORCIDs, you add those in DESCRIPTION as follows:

```
person("Research Institute for Nature and Forest (INBO)", role = "cph",
           comment = c(ROR = "00j54wy13")),
```

The [ROR landing page for INBO](https://ror.org/00j54wy13) links out to acronym, Dutch name, website, etc. The location will be updated by Bart Goossens (also useful for Zenodo).

Since a ROR ID creates strongly linked data, I think it's worthwhile to recommend and enforce with _checklist_. I would recommend this _instead of_ enforcing the info@inbo.be email for INBO.

From:

> `Research Institute for Nature and Forest (INBO)` must be listed as copyright holder and use `info@inbo.be` as email.

To:

> `Research Institute for Nature and Forest (INBO)` must be listed as copyright holder and use `c(ROR = "00j54wy13")` as comment.

PS: I was notified of this practice by its support in [pkgdown 2.1.2](https://github.com/r-lib/pkgdown/releases/tag/v2.1.2).

**Comment by wlangera** [comment]
Adding the ROR identifiers as such currently results in 2 checklist warnings.
They can be ignored in the `checklist.yml` file.

```yml
  - motivation: Checklist issue [153](https://github.com/inbo/checklist/issues/153)
    value: '`Research Institute for Nature and Forest (INBO)` must be listed as copyright
      holder and use `info@inbo.be` as email.'
  - motivation: Not applicable
    value: ORCID required for `Research Institute for Nature and Forest (INBO)`
```

**Comment by ThierryO** [comment]
I am in favour of adding the ROR. What's the rationale behind dropping the e-mail. Current we use the e-mail information to determine the affiliation.

**Comment by peterdesmet** [comment]
I find the email for a copyright holder somewhat superfluous (especially as mandatory info). Can you elaborate how you use the email for affiliation (of whom)?

**Comment by ThierryO** [comment]
For every project, you can define the [organisations](https://inbo.github.io/checklist/articles/organisation.html). We use to email domain to check who belongs to which organisation.

**Comment by peterdesmet** [comment]
I see, so the email (domain) is defined in `organisation.yml` (or `info@inbo.be` by default). In that case, I would:

- Continue to have additional checks (e.g. ORCID) for `Authors@R` with the same email domain.
- Not require an email (or ORCID) for `fnd` and `cph`.

**Comment by ThierryO** [comment]
I wrote the [technical requirements](https://github.com/inbo/checklist/blob/0.4.3/vignettes/organisation.Rmd#L80) for the `organisation.yml`. The idea is that every organisation can define their own set of rules in https://github.com/`org_name`/checklist/organisation.yml. Feedback is welcome.

**Comment by peterdesmet** [comment]
Some feedback:

1. An example of the organisation.yml in organisation.Rmd would be really helpful. You could indicate with comments what is required and what is not.

2. It took me a while to understand that the [technical requirements](https://github.com/inbo/checklist/blob/4c1fb1180a792c17fb6ea25e98cac34fe6044dcf/vignettes/organisation.Rmd#L80) describe the properties one can find in `organisation.yml`, but also what is needed in DESCRIPTION. An example `Authors@R` might be useful.

3. I would define affiliation rules, rightsholder, funders separately. Here's my take on an `organisation.yml` that would work for our packages:

```yml
organisation: # Primary organisation, used to set some defaults
  name: "Research Institute for Nature and Forest (INBO)" # Multiple names not used, match is made on domain, see further
  github: inbo
  zenodo: inbo # or "community"
  # email: not used

affiliations:
- domain: inbo.be # I would this to match Authors@R
  name: Research Institute for Nature and Forest (INBO) # This is how affiliation should be written
  orcid: yes
- domain: vlaanderen.be
  name: Vlaamse overheid
  orcid: no

rightsholders: # If defined, need to be present in DESCRIPTION
- name: Research Institute for Nature and Forest (INBO)
  ror: 00j54wy13 # Overwrites website if defined

funders:
- name: European Union
  website: https://doi.org/10.3030/101059592
- name: LIFE RIPARIAS
  website: https://www.riparias.be
```
